name: Java CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'
          java-package: jdk
          check-latest: false
          server-id: github
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.GITHUB_TOKEN }}
          overwrite-settings: true

      - name: Install Maven
        run: |
          sudo apt update
          sudo apt install -y maven

      - name: Build with Maven
        run: |
          mvn clean install
          ls target
          
      - name: Deploy to EC2
        run: |
          scp -i test.pem -o StrictHostKeyChecking=no target/valaxy-2.0-RELEASE.war ubuntu@3.133.91.158:/home/ubentu/
          # ssh -i test.pem -o StrictHostKeyChecking=no ubuntu@3.133.91.158 'bash -s' < ./deploy/deploy.sh
        env:
          JAVA_HOME: ${{ env.JAVA_HOME }}
          JAVA_HOME_11_X64: ${{ env.JAVA_HOME_11_X64 }}
